name: 'deployments-action'
description: 'Cancel redundant actions'
inputs:
  access_token:
    description: 'Github token'
    required: true
  environment:
    description: 'Environments name'
    required: true
  environment_url:
    description: 'Environments url'
    required: false
  state:
    description: 'Deployments state'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
